source 'https://rubygems.org'

source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sqlite3'
gem 'jquery-rails'
gem 'jquery-datatables-rails'
gem 'haml-rails'
gem 'sorcery'
gem 'pg'
gem 'protected_attributes'
gem 'will_paginate', '~> 3.0'
gem 'sass', '~> 3.3.11'
gem 'coffee-script', '~> 2.3.0'
group :test do
  gem 'capybara'
  gem 'launchy'
end

group :development, :test do
  gem 'faker'
end
